=== Lounis06/m1gil/M1F/WEB2/Projet/src/main/resources/sepa.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://univ.fr/sepa" xmlns="http://univ.fr/sepa">
	
	<!-- Liste des éléments disponibles -->
	<xs:element name="CstmrDrctDbtInitn" type="CstmrDrctDbtInitnType"/>
	<xs:element name="DrctDbtTxInf" type="DrctDbtTxInfType" />
	<xs:element name="PmtInf" type="xs:string" />
	<xs:element name="InstdAmt" type="InstdAmtType" />
	<xs:element name="DrctDbtTx" type="DrctDbtTxType" />
	<xs:element name="DbtrAgt" type="DbtrAgtType" />
	<xs:element name="Dbtr" type="DbtrType" />
	<xs:element name="DbtrAcct" type="DbtrAcctType" />
	<xs:element name="RmtInf" type="xs:string" />
	<xs:element name="DBID" type="DBIDType" />
	
	
	<!-- Liste des types simples -->
	<xs:simpleType name="Amount">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="2" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="Max35Text">
		<xs:restriction base="xs:string">
			<xs:maxLength value="35" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="CcyType">
		<xs:restriction base="xs:string">
			 <xs:pattern value="[A-Z]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="IBANType">
		<xs:restriction base="xs:string">
			 <xs:pattern value="[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="BICType">
		<xs:restriction base="xs:string">
			 <xs:pattern value="[A-Z]{8}|[A-Z]{11}"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="DBIDType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Z]{2}[0-9]{4}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="SEPAType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SEPA" />
		</xs:restriction>
	</xs:simpleType>
	
	
	<!-- Liste des types complexes d'éléments -->
	<xs:complexType name="CstmrDrctDbtInitnType">
		<xs:sequence>
			<xs:element name="DrctDbtTxInf" type="DrctDbtTxInfType" minOccurs="1" maxOccurs="10"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="DrctDbtTxInfType">
		<xs:sequence>
			<xs:element name="DBID" type="DBIDType" />
			<xs:element name="PmtInf" type="xs:string" />
			<xs:element name="InstdAmt" type="InstdAmtType" />
			<xs:element name="DrctDbtTx" type="DrctDbtTxType" />
			<xs:element name="DbtrAgt" type="DbtrAgtType" />
			<xs:element name="Dbtr" type="DbtrType" />
			<xs:element name="DbtrAcct" type="DbtrAcctType" />
			<xs:element name="RmtInf" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="InstdAmtType">
		<xs:sequence>
			<xs:element name="amount" type="Amount"></xs:element>
		</xs:sequence>
		<xs:attribute name="Ccy" type="CcyType"></xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="DrctDbtTxType">
		<xs:sequence>
			<xs:element name="MndtId" type="Max35Text" />
			<xs:element name="DtOfSgntr" type="xs:dateTime" />
		</xs:sequence>
	</xs:complexType>
			
	<xs:complexType name="DbtrAgtType">
		<xs:choice>
			<xs:element name="BIC" type="BICType" />
			<xs:element name ="Othr" type="OthrType" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="OthrType">
		<xs:sequence>
			<xs:element name="Id" type="Max35Text" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="DbtrType">
		<xs:sequence>
			<xs:element name="Nm" type="Max35Text" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="DbtrAcctType">
		<xs:choice>
			<xs:element name="IBAN" type="IBANType" />
			<xs:element name="PrvtId" type="PrvtIdType" />
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="PrvtIdType">
		<xs:sequence>
			<xs:element name="Othr" type="OthrType2" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="OthrType2">
		<xs:sequence>
			<xs:element name="Id" type="Max35Text" />
			<xs:element name="SchmeNm" type="SchmeNmType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SchmeNmType">
		<xs:sequence>
			<xs:element name="Prtry" type="SEPAType" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== Lounis06/m1gil/M1F/WEB2/Projet/src/main/resources/sepa.xml
<?xml version="1.0" encoding="UTF-8"?><p:CstmrDrctDbtInitn xmlns:p="http://univ.fr/sepa" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://univ.fr/sepa sepa.xsd ">
  <DrctDbtTxInf>
    <DBID>CP0001</DBID>
    <PmtInf>
      REF OPE test
    </PmtInf>
    <InstdAmt Ccy="EUR">
      <amount>1100.07</amount>
    </InstdAmt>
    <DrctDbtTx>
      <MndtId>MANDAT NO 55555</MndtId>
      <DtOfSgntr>2009-09-01T16:45:00</DtOfSgntr>
    </DrctDbtTx>
    <DbtrAgt>
      <Othr><Id>NOTPROVIDED</Id></Othr>
    </DbtrAgt>
    <Dbtr>
      <Nm>Mr Debiteur N1</Nm>
    </Dbtr>
    <DbtrAcct>
      <IBAN>FR763004136210001234567811</IBAN>
    </DbtrAcct>
    <RmtInf>
      Facture N1
    </RmtInf>
  </DrctDbtTxInf>
  
  <DrctDbtTxInf>
    <DBID>CP0002</DBID>
    <PmtInf>
      REF OPE BBBB
    </PmtInf>
    <InstdAmt Ccy="EUR">
      <amount>2150.08</amount>
    </InstdAmt>
    <DrctDbtTx>
      <MndtId>MANDAT NO 666666</MndtId>
      <DtOfSgntr>1989-07-03T22:24:17</DtOfSgntr>
    </DrctDbtTx>
    <DbtrAgt>
      <BIC>BANKGBALABC</BIC>
    </DbtrAgt>
    <Dbtr>
      <Nm>Mr Debiteur N2</Nm>
    </Dbtr>
    <DbtrAcct>
      <IBAN>GB29NWBK60161331926819</IBAN>
    </DbtrAcct>
    <RmtInf>
      Facture Reference ISO 654321
    </RmtInf>
  </DrctDbtTxInf>
</p:CstmrDrctDbtInitn>
